# Generated by Django 3.0.8 on 2020-10-10 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainBlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniturecard',
            name='img_picture',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
