# Generated by Django 3.0.8 on 2020-10-11 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainBlog', '0002_auto_20201011_0047'),
    ]

    operations = [
        migrations.CreateModel(
            name='FurnitureCardTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('anons', models.TextField()),
                ('img_picture_1', models.ImageField(upload_to='images/')),
                ('img_picture_2', models.ImageField(upload_to='images/')),
                ('img_picture_3', models.ImageField(upload_to='images/')),
                ('description', models.TextField()),
            ],
        ),
    ]
