# Generated by Django 3.0.8 on 2020-10-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainBlog', '0003_furniturecardtwo'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniturecardtwo',
            name='price',
            field=models.CharField(default='', max_length=50),
        ),
    ]
